version: '3.8'
services: 
    angular-service: 
      container_name: angularcontainer  
      build: .
      ports: 
        - '4200:4200'
      command:
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"