version: "3.8"
services:

  app:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: cep_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 15

  angular-service: 
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports: 
      - '4200:4200'
    command:
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    depends_on:
      - app