version: "3.8"
services:

  app:
    container_name: app
    build: .
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: cep_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 15
